// Code generated by ent, DO NOT EDIT.

package matchings

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the matchings type in the database.
	Label = "matchings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldMatchedUserID holds the string denoting the matched_user_id field in the database.
	FieldMatchedUserID = "matched_user_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldMatchedAt holds the string denoting the matched_at field in the database.
	FieldMatchedAt = "matched_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeMember holds the string denoting the member edge name in mutations.
	EdgeMember = "member"
	// EdgeHad holds the string denoting the had edge name in mutations.
	EdgeHad = "had"
	// EdgeMakes holds the string denoting the makes edge name in mutations.
	EdgeMakes = "makes"
	// Table holds the table name of the matchings in the database.
	Table = "matching_ss"
	// MemberTable is the table that holds the member relation/edge. The primary key declared below.
	MemberTable = "users_participates"
	// MemberInverseTable is the table name for the USERS entity.
	// It exists in this package in order to avoid circular dependency with the "users" package.
	MemberInverseTable = "user_ss"
	// HadTable is the table that holds the had relation/edge.
	HadTable = "matching_ss"
	// HadInverseTable is the table name for the SESSIONS entity.
	// It exists in this package in order to avoid circular dependency with the "sessions" package.
	HadInverseTable = "session_ss"
	// HadColumn is the table column denoting the had relation/edge.
	HadColumn = "sessions_has"
	// MakesTable is the table that holds the makes relation/edge.
	MakesTable = "call_ss"
	// MakesInverseTable is the table name for the CALLS entity.
	// It exists in this package in order to avoid circular dependency with the "calls" package.
	MakesInverseTable = "call_ss"
	// MakesColumn is the table column denoting the makes relation/edge.
	MakesColumn = "matchings_makes"
)

// Columns holds all SQL columns for matchings fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldMatchedUserID,
	FieldSessionID,
	FieldMatchedAt,
	FieldStatus,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "matching_ss"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"sessions_has",
}

var (
	// MemberPrimaryKey and MemberColumn2 are the table columns denoting the
	// primary key for the member relation (M2M).
	MemberPrimaryKey = []string{"users_id", "matchings_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultMatchedAt holds the default value on creation for the "matched_at" field.
	DefaultMatchedAt time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusMATCHED     Status = "MATCHED"
	StatusPROCCESSING Status = "PROCCESSING"
	StatusFINISHED    Status = "FINISHED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusMATCHED, StatusPROCCESSING, StatusFINISHED:
		return nil
	default:
		return fmt.Errorf("matchings: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the MATCHINGS queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByMatchedUserID orders the results by the matched_user_id field.
func ByMatchedUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchedUserID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByMatchedAt orders the results by the matched_at field.
func ByMatchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMemberCount orders the results by member count.
func ByMemberCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMemberStep(), opts...)
	}
}

// ByMember orders the results by member terms.
func ByMember(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMemberStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByHadField orders the results by had field.
func ByHadField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHadStep(), sql.OrderByField(field, opts...))
	}
}

// ByMakesField orders the results by makes field.
func ByMakesField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMakesStep(), sql.OrderByField(field, opts...))
	}
}
func newMemberStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MemberInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, MemberTable, MemberPrimaryKey...),
	)
}
func newHadStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HadInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, HadTable, HadColumn),
	)
}
func newMakesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MakesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, MakesTable, MakesColumn),
	)
}
