// Code generated by ent, DO NOT EDIT.

package ai_themes

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Hosi121/SpeakUp/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldLTE(FieldID, id))
}

// ThemeText applies equality check predicate on the "theme_text" field. It's identical to ThemeTextEQ.
func ThemeText(v string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldEQ(FieldThemeText, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldEQ(FieldCreatedAt, v))
}

// ThemeTextEQ applies the EQ predicate on the "theme_text" field.
func ThemeTextEQ(v string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldEQ(FieldThemeText, v))
}

// ThemeTextNEQ applies the NEQ predicate on the "theme_text" field.
func ThemeTextNEQ(v string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldNEQ(FieldThemeText, v))
}

// ThemeTextIn applies the In predicate on the "theme_text" field.
func ThemeTextIn(vs ...string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldIn(FieldThemeText, vs...))
}

// ThemeTextNotIn applies the NotIn predicate on the "theme_text" field.
func ThemeTextNotIn(vs ...string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldNotIn(FieldThemeText, vs...))
}

// ThemeTextGT applies the GT predicate on the "theme_text" field.
func ThemeTextGT(v string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldGT(FieldThemeText, v))
}

// ThemeTextGTE applies the GTE predicate on the "theme_text" field.
func ThemeTextGTE(v string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldGTE(FieldThemeText, v))
}

// ThemeTextLT applies the LT predicate on the "theme_text" field.
func ThemeTextLT(v string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldLT(FieldThemeText, v))
}

// ThemeTextLTE applies the LTE predicate on the "theme_text" field.
func ThemeTextLTE(v string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldLTE(FieldThemeText, v))
}

// ThemeTextContains applies the Contains predicate on the "theme_text" field.
func ThemeTextContains(v string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldContains(FieldThemeText, v))
}

// ThemeTextHasPrefix applies the HasPrefix predicate on the "theme_text" field.
func ThemeTextHasPrefix(v string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldHasPrefix(FieldThemeText, v))
}

// ThemeTextHasSuffix applies the HasSuffix predicate on the "theme_text" field.
func ThemeTextHasSuffix(v string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldHasSuffix(FieldThemeText, v))
}

// ThemeTextEqualFold applies the EqualFold predicate on the "theme_text" field.
func ThemeTextEqualFold(v string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldEqualFold(FieldThemeText, v))
}

// ThemeTextContainsFold applies the ContainsFold predicate on the "theme_text" field.
func ThemeTextContainsFold(v string) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldContainsFold(FieldThemeText, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUsed applies the HasEdge predicate on the "used" edge.
func HasUsed() predicate.AI_THEMES {
	return predicate.AI_THEMES(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, UsedTable, UsedColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsedWith applies the HasEdge predicate on the "used" edge with a given conditions (other predicates).
func HasUsedWith(preds ...predicate.EVENTS) predicate.AI_THEMES {
	return predicate.AI_THEMES(func(s *sql.Selector) {
		step := newUsedStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AI_THEMES) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AI_THEMES) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AI_THEMES) predicate.AI_THEMES {
	return predicate.AI_THEMES(sql.NotPredicates(p))
}
