// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Hosi121/SpeakUp/ent/calls"
	"github.com/Hosi121/SpeakUp/ent/matchings"
	"github.com/Hosi121/SpeakUp/ent/predicate"
)

// CALLSQuery is the builder for querying CALLS entities.
type CALLSQuery struct {
	config
	ctx        *QueryContext
	order      []calls.OrderOption
	inters     []Interceptor
	predicates []predicate.CALLS
	withMade   *MATCHINGSQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CALLSQuery builder.
func (cq *CALLSQuery) Where(ps ...predicate.CALLS) *CALLSQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *CALLSQuery) Limit(limit int) *CALLSQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *CALLSQuery) Offset(offset int) *CALLSQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *CALLSQuery) Unique(unique bool) *CALLSQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *CALLSQuery) Order(o ...calls.OrderOption) *CALLSQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryMade chains the current query on the "made" edge.
func (cq *CALLSQuery) QueryMade() *MATCHINGSQuery {
	query := (&MATCHINGSClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(calls.Table, calls.FieldID, selector),
			sqlgraph.To(matchings.Table, matchings.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, calls.MadeTable, calls.MadeColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CALLS entity from the query.
// Returns a *NotFoundError when no CALLS was found.
func (cq *CALLSQuery) First(ctx context.Context) (*CALLS, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{calls.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *CALLSQuery) FirstX(ctx context.Context) *CALLS {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CALLS ID from the query.
// Returns a *NotFoundError when no CALLS ID was found.
func (cq *CALLSQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{calls.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *CALLSQuery) FirstIDX(ctx context.Context) int {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CALLS entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CALLS entity is found.
// Returns a *NotFoundError when no CALLS entities are found.
func (cq *CALLSQuery) Only(ctx context.Context) (*CALLS, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{calls.Label}
	default:
		return nil, &NotSingularError{calls.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *CALLSQuery) OnlyX(ctx context.Context) *CALLS {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CALLS ID in the query.
// Returns a *NotSingularError when more than one CALLS ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *CALLSQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{calls.Label}
	default:
		err = &NotSingularError{calls.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *CALLSQuery) OnlyIDX(ctx context.Context) int {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CALLSs.
func (cq *CALLSQuery) All(ctx context.Context) ([]*CALLS, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryAll)
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CALLS, *CALLSQuery]()
	return withInterceptors[[]*CALLS](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *CALLSQuery) AllX(ctx context.Context) []*CALLS {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CALLS IDs.
func (cq *CALLSQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryIDs)
	if err = cq.Select(calls.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *CALLSQuery) IDsX(ctx context.Context) []int {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *CALLSQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryCount)
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*CALLSQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *CALLSQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *CALLSQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryExist)
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *CALLSQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CALLSQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *CALLSQuery) Clone() *CALLSQuery {
	if cq == nil {
		return nil
	}
	return &CALLSQuery{
		config:     cq.config,
		ctx:        cq.ctx.Clone(),
		order:      append([]calls.OrderOption{}, cq.order...),
		inters:     append([]Interceptor{}, cq.inters...),
		predicates: append([]predicate.CALLS{}, cq.predicates...),
		withMade:   cq.withMade.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithMade tells the query-builder to eager-load the nodes that are connected to
// the "made" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CALLSQuery) WithMade(opts ...func(*MATCHINGSQuery)) *CALLSQuery {
	query := (&MATCHINGSClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withMade = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SessionID int `json:"session_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CALLS.Query().
//		GroupBy(calls.FieldSessionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *CALLSQuery) GroupBy(field string, fields ...string) *CALLSGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CALLSGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = calls.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SessionID int `json:"session_id,omitempty"`
//	}
//
//	client.CALLS.Query().
//		Select(calls.FieldSessionID).
//		Scan(ctx, &v)
func (cq *CALLSQuery) Select(fields ...string) *CALLSSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &CALLSSelect{CALLSQuery: cq}
	sbuild.label = calls.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CALLSSelect configured with the given aggregations.
func (cq *CALLSQuery) Aggregate(fns ...AggregateFunc) *CALLSSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *CALLSQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !calls.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *CALLSQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CALLS, error) {
	var (
		nodes       = []*CALLS{}
		withFKs     = cq.withFKs
		_spec       = cq.querySpec()
		loadedTypes = [1]bool{
			cq.withMade != nil,
		}
	)
	if cq.withMade != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, calls.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CALLS).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CALLS{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withMade; query != nil {
		if err := cq.loadMade(ctx, query, nodes, nil,
			func(n *CALLS, e *MATCHINGS) { n.Edges.Made = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *CALLSQuery) loadMade(ctx context.Context, query *MATCHINGSQuery, nodes []*CALLS, init func(*CALLS), assign func(*CALLS, *MATCHINGS)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CALLS)
	for i := range nodes {
		if nodes[i].matchings_makes == nil {
			continue
		}
		fk := *nodes[i].matchings_makes
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(matchings.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "matchings_makes" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (cq *CALLSQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *CALLSQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(calls.Table, calls.Columns, sqlgraph.NewFieldSpec(calls.FieldID, field.TypeInt))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, calls.FieldID)
		for i := range fields {
			if fields[i] != calls.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *CALLSQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(calls.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = calls.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CALLSGroupBy is the group-by builder for CALLS entities.
type CALLSGroupBy struct {
	selector
	build *CALLSQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *CALLSGroupBy) Aggregate(fns ...AggregateFunc) *CALLSGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *CALLSGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, ent.OpQueryGroupBy)
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CALLSQuery, *CALLSGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *CALLSGroupBy) sqlScan(ctx context.Context, root *CALLSQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CALLSSelect is the builder for selecting fields of CALLS entities.
type CALLSSelect struct {
	*CALLSQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *CALLSSelect) Aggregate(fns ...AggregateFunc) *CALLSSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *CALLSSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, ent.OpQuerySelect)
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CALLSQuery, *CALLSSelect](ctx, cs.CALLSQuery, cs, cs.inters, v)
}

func (cs *CALLSSelect) sqlScan(ctx context.Context, root *CALLSQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
