// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Hosi121/SpeakUp/ent/predicate"
	"github.com/Hosi121/SpeakUp/ent/progress"
	"github.com/Hosi121/SpeakUp/ent/users"
)

// PROGRESSQuery is the builder for querying PROGRESS entities.
type PROGRESSQuery struct {
	config
	ctx          *QueryContext
	order        []progress.OrderOption
	inters       []Interceptor
	predicates   []predicate.PROGRESS
	withRecorded *USERSQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PROGRESSQuery builder.
func (pq *PROGRESSQuery) Where(ps ...predicate.PROGRESS) *PROGRESSQuery {
	pq.predicates = append(pq.predicates, ps...)
	return pq
}

// Limit the number of records to be returned by this query.
func (pq *PROGRESSQuery) Limit(limit int) *PROGRESSQuery {
	pq.ctx.Limit = &limit
	return pq
}

// Offset to start from.
func (pq *PROGRESSQuery) Offset(offset int) *PROGRESSQuery {
	pq.ctx.Offset = &offset
	return pq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pq *PROGRESSQuery) Unique(unique bool) *PROGRESSQuery {
	pq.ctx.Unique = &unique
	return pq
}

// Order specifies how the records should be ordered.
func (pq *PROGRESSQuery) Order(o ...progress.OrderOption) *PROGRESSQuery {
	pq.order = append(pq.order, o...)
	return pq
}

// QueryRecorded chains the current query on the "recorded" edge.
func (pq *PROGRESSQuery) QueryRecorded() *USERSQuery {
	query := (&USERSClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(progress.Table, progress.FieldID, selector),
			sqlgraph.To(users.Table, users.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, progress.RecordedTable, progress.RecordedColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PROGRESS entity from the query.
// Returns a *NotFoundError when no PROGRESS was found.
func (pq *PROGRESSQuery) First(ctx context.Context) (*PROGRESS, error) {
	nodes, err := pq.Limit(1).All(setContextOp(ctx, pq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{progress.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pq *PROGRESSQuery) FirstX(ctx context.Context) *PROGRESS {
	node, err := pq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PROGRESS ID from the query.
// Returns a *NotFoundError when no PROGRESS ID was found.
func (pq *PROGRESSQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pq.Limit(1).IDs(setContextOp(ctx, pq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{progress.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pq *PROGRESSQuery) FirstIDX(ctx context.Context) int {
	id, err := pq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PROGRESS entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PROGRESS entity is found.
// Returns a *NotFoundError when no PROGRESS entities are found.
func (pq *PROGRESSQuery) Only(ctx context.Context) (*PROGRESS, error) {
	nodes, err := pq.Limit(2).All(setContextOp(ctx, pq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{progress.Label}
	default:
		return nil, &NotSingularError{progress.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pq *PROGRESSQuery) OnlyX(ctx context.Context) *PROGRESS {
	node, err := pq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PROGRESS ID in the query.
// Returns a *NotSingularError when more than one PROGRESS ID is found.
// Returns a *NotFoundError when no entities are found.
func (pq *PROGRESSQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pq.Limit(2).IDs(setContextOp(ctx, pq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{progress.Label}
	default:
		err = &NotSingularError{progress.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pq *PROGRESSQuery) OnlyIDX(ctx context.Context) int {
	id, err := pq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PROGRESSs.
func (pq *PROGRESSQuery) All(ctx context.Context) ([]*PROGRESS, error) {
	ctx = setContextOp(ctx, pq.ctx, ent.OpQueryAll)
	if err := pq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PROGRESS, *PROGRESSQuery]()
	return withInterceptors[[]*PROGRESS](ctx, pq, qr, pq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pq *PROGRESSQuery) AllX(ctx context.Context) []*PROGRESS {
	nodes, err := pq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PROGRESS IDs.
func (pq *PROGRESSQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pq.ctx.Unique == nil && pq.path != nil {
		pq.Unique(true)
	}
	ctx = setContextOp(ctx, pq.ctx, ent.OpQueryIDs)
	if err = pq.Select(progress.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pq *PROGRESSQuery) IDsX(ctx context.Context) []int {
	ids, err := pq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pq *PROGRESSQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pq.ctx, ent.OpQueryCount)
	if err := pq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pq, querierCount[*PROGRESSQuery](), pq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pq *PROGRESSQuery) CountX(ctx context.Context) int {
	count, err := pq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pq *PROGRESSQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pq.ctx, ent.OpQueryExist)
	switch _, err := pq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pq *PROGRESSQuery) ExistX(ctx context.Context) bool {
	exist, err := pq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PROGRESSQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pq *PROGRESSQuery) Clone() *PROGRESSQuery {
	if pq == nil {
		return nil
	}
	return &PROGRESSQuery{
		config:       pq.config,
		ctx:          pq.ctx.Clone(),
		order:        append([]progress.OrderOption{}, pq.order...),
		inters:       append([]Interceptor{}, pq.inters...),
		predicates:   append([]predicate.PROGRESS{}, pq.predicates...),
		withRecorded: pq.withRecorded.Clone(),
		// clone intermediate query.
		sql:  pq.sql.Clone(),
		path: pq.path,
	}
}

// WithRecorded tells the query-builder to eager-load the nodes that are connected to
// the "recorded" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PROGRESSQuery) WithRecorded(opts ...func(*USERSQuery)) *PROGRESSQuery {
	query := (&USERSClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withRecorded = query
	return pq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PROGRESS.Query().
//		GroupBy(progress.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pq *PROGRESSQuery) GroupBy(field string, fields ...string) *PROGRESSGroupBy {
	pq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PROGRESSGroupBy{build: pq}
	grbuild.flds = &pq.ctx.Fields
	grbuild.label = progress.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.PROGRESS.Query().
//		Select(progress.FieldUserID).
//		Scan(ctx, &v)
func (pq *PROGRESSQuery) Select(fields ...string) *PROGRESSSelect {
	pq.ctx.Fields = append(pq.ctx.Fields, fields...)
	sbuild := &PROGRESSSelect{PROGRESSQuery: pq}
	sbuild.label = progress.Label
	sbuild.flds, sbuild.scan = &pq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PROGRESSSelect configured with the given aggregations.
func (pq *PROGRESSQuery) Aggregate(fns ...AggregateFunc) *PROGRESSSelect {
	return pq.Select().Aggregate(fns...)
}

func (pq *PROGRESSQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pq); err != nil {
				return err
			}
		}
	}
	for _, f := range pq.ctx.Fields {
		if !progress.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pq.path != nil {
		prev, err := pq.path(ctx)
		if err != nil {
			return err
		}
		pq.sql = prev
	}
	return nil
}

func (pq *PROGRESSQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PROGRESS, error) {
	var (
		nodes       = []*PROGRESS{}
		withFKs     = pq.withFKs
		_spec       = pq.querySpec()
		loadedTypes = [1]bool{
			pq.withRecorded != nil,
		}
	)
	if pq.withRecorded != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, progress.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PROGRESS).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PROGRESS{config: pq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pq.withRecorded; query != nil {
		if err := pq.loadRecorded(ctx, query, nodes, nil,
			func(n *PROGRESS, e *USERS) { n.Edges.Recorded = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pq *PROGRESSQuery) loadRecorded(ctx context.Context, query *USERSQuery, nodes []*PROGRESS, init func(*PROGRESS), assign func(*PROGRESS, *USERS)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PROGRESS)
	for i := range nodes {
		if nodes[i].users_records == nil {
			continue
		}
		fk := *nodes[i].users_records
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(users.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "users_records" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pq *PROGRESSQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pq.querySpec()
	_spec.Node.Columns = pq.ctx.Fields
	if len(pq.ctx.Fields) > 0 {
		_spec.Unique = pq.ctx.Unique != nil && *pq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pq.driver, _spec)
}

func (pq *PROGRESSQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(progress.Table, progress.Columns, sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt))
	_spec.From = pq.sql
	if unique := pq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pq.path != nil {
		_spec.Unique = true
	}
	if fields := pq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, progress.FieldID)
		for i := range fields {
			if fields[i] != progress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pq *PROGRESSQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pq.driver.Dialect())
	t1 := builder.Table(progress.Table)
	columns := pq.ctx.Fields
	if len(columns) == 0 {
		columns = progress.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pq.sql != nil {
		selector = pq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pq.ctx.Unique != nil && *pq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pq.predicates {
		p(selector)
	}
	for _, p := range pq.order {
		p(selector)
	}
	if offset := pq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PROGRESSGroupBy is the group-by builder for PROGRESS entities.
type PROGRESSGroupBy struct {
	selector
	build *PROGRESSQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pgb *PROGRESSGroupBy) Aggregate(fns ...AggregateFunc) *PROGRESSGroupBy {
	pgb.fns = append(pgb.fns, fns...)
	return pgb
}

// Scan applies the selector query and scans the result into the given value.
func (pgb *PROGRESSGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pgb.build.ctx, ent.OpQueryGroupBy)
	if err := pgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PROGRESSQuery, *PROGRESSGroupBy](ctx, pgb.build, pgb, pgb.build.inters, v)
}

func (pgb *PROGRESSGroupBy) sqlScan(ctx context.Context, root *PROGRESSQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pgb.fns))
	for _, fn := range pgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pgb.flds)+len(pgb.fns))
		for _, f := range *pgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PROGRESSSelect is the builder for selecting fields of PROGRESS entities.
type PROGRESSSelect struct {
	*PROGRESSQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ps *PROGRESSSelect) Aggregate(fns ...AggregateFunc) *PROGRESSSelect {
	ps.fns = append(ps.fns, fns...)
	return ps
}

// Scan applies the selector query and scans the result into the given value.
func (ps *PROGRESSSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ps.ctx, ent.OpQuerySelect)
	if err := ps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PROGRESSQuery, *PROGRESSSelect](ctx, ps.PROGRESSQuery, ps, ps.inters, v)
}

func (ps *PROGRESSSelect) sqlScan(ctx context.Context, root *PROGRESSQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ps.fns))
	for _, fn := range ps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
