// Code generated by ent, DO NOT EDIT.

package trophies

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Hosi121/SpeakUp/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldEQ(FieldTitle, v))
}

// Contents applies equality check predicate on the "contents" field. It's identical to ContentsEQ.
func Contents(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldEQ(FieldContents, v))
}

// Requirement applies equality check predicate on the "requirement" field. It's identical to RequirementEQ.
func Requirement(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldEQ(FieldRequirement, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldContainsFold(FieldTitle, v))
}

// ContentsEQ applies the EQ predicate on the "contents" field.
func ContentsEQ(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldEQ(FieldContents, v))
}

// ContentsNEQ applies the NEQ predicate on the "contents" field.
func ContentsNEQ(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldNEQ(FieldContents, v))
}

// ContentsIn applies the In predicate on the "contents" field.
func ContentsIn(vs ...string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldIn(FieldContents, vs...))
}

// ContentsNotIn applies the NotIn predicate on the "contents" field.
func ContentsNotIn(vs ...string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldNotIn(FieldContents, vs...))
}

// ContentsGT applies the GT predicate on the "contents" field.
func ContentsGT(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldGT(FieldContents, v))
}

// ContentsGTE applies the GTE predicate on the "contents" field.
func ContentsGTE(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldGTE(FieldContents, v))
}

// ContentsLT applies the LT predicate on the "contents" field.
func ContentsLT(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldLT(FieldContents, v))
}

// ContentsLTE applies the LTE predicate on the "contents" field.
func ContentsLTE(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldLTE(FieldContents, v))
}

// ContentsContains applies the Contains predicate on the "contents" field.
func ContentsContains(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldContains(FieldContents, v))
}

// ContentsHasPrefix applies the HasPrefix predicate on the "contents" field.
func ContentsHasPrefix(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldHasPrefix(FieldContents, v))
}

// ContentsHasSuffix applies the HasSuffix predicate on the "contents" field.
func ContentsHasSuffix(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldHasSuffix(FieldContents, v))
}

// ContentsEqualFold applies the EqualFold predicate on the "contents" field.
func ContentsEqualFold(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldEqualFold(FieldContents, v))
}

// ContentsContainsFold applies the ContainsFold predicate on the "contents" field.
func ContentsContainsFold(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldContainsFold(FieldContents, v))
}

// RequirementEQ applies the EQ predicate on the "requirement" field.
func RequirementEQ(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldEQ(FieldRequirement, v))
}

// RequirementNEQ applies the NEQ predicate on the "requirement" field.
func RequirementNEQ(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldNEQ(FieldRequirement, v))
}

// RequirementIn applies the In predicate on the "requirement" field.
func RequirementIn(vs ...string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldIn(FieldRequirement, vs...))
}

// RequirementNotIn applies the NotIn predicate on the "requirement" field.
func RequirementNotIn(vs ...string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldNotIn(FieldRequirement, vs...))
}

// RequirementGT applies the GT predicate on the "requirement" field.
func RequirementGT(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldGT(FieldRequirement, v))
}

// RequirementGTE applies the GTE predicate on the "requirement" field.
func RequirementGTE(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldGTE(FieldRequirement, v))
}

// RequirementLT applies the LT predicate on the "requirement" field.
func RequirementLT(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldLT(FieldRequirement, v))
}

// RequirementLTE applies the LTE predicate on the "requirement" field.
func RequirementLTE(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldLTE(FieldRequirement, v))
}

// RequirementContains applies the Contains predicate on the "requirement" field.
func RequirementContains(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldContains(FieldRequirement, v))
}

// RequirementHasPrefix applies the HasPrefix predicate on the "requirement" field.
func RequirementHasPrefix(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldHasPrefix(FieldRequirement, v))
}

// RequirementHasSuffix applies the HasSuffix predicate on the "requirement" field.
func RequirementHasSuffix(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldHasSuffix(FieldRequirement, v))
}

// RequirementEqualFold applies the EqualFold predicate on the "requirement" field.
func RequirementEqualFold(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldEqualFold(FieldRequirement, v))
}

// RequirementContainsFold applies the ContainsFold predicate on the "requirement" field.
func RequirementContainsFold(v string) predicate.TROPHIES {
	return predicate.TROPHIES(sql.FieldContainsFold(FieldRequirement, v))
}

// HasRefered applies the HasEdge predicate on the "refered" edge.
func HasRefered() predicate.TROPHIES {
	return predicate.TROPHIES(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ReferedTable, ReferedColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReferedWith applies the HasEdge predicate on the "refered" edge with a given conditions (other predicates).
func HasReferedWith(preds ...predicate.ACHIEVEMENTS) predicate.TROPHIES {
	return predicate.TROPHIES(func(s *sql.Selector) {
		step := newReferedStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TROPHIES) predicate.TROPHIES {
	return predicate.TROPHIES(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TROPHIES) predicate.TROPHIES {
	return predicate.TROPHIES(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TROPHIES) predicate.TROPHIES {
	return predicate.TROPHIES(sql.NotPredicates(p))
}
