// Code generated by ent, DO NOT EDIT.

package achievements

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Hosi121/SpeakUp/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldEQ(FieldUserID, v))
}

// TrophyID applies equality check predicate on the "trophy_id" field. It's identical to TrophyIDEQ.
func TrophyID(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldEQ(FieldTrophyID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldLTE(FieldUserID, v))
}

// TrophyIDEQ applies the EQ predicate on the "trophy_id" field.
func TrophyIDEQ(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldEQ(FieldTrophyID, v))
}

// TrophyIDNEQ applies the NEQ predicate on the "trophy_id" field.
func TrophyIDNEQ(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldNEQ(FieldTrophyID, v))
}

// TrophyIDIn applies the In predicate on the "trophy_id" field.
func TrophyIDIn(vs ...int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldIn(FieldTrophyID, vs...))
}

// TrophyIDNotIn applies the NotIn predicate on the "trophy_id" field.
func TrophyIDNotIn(vs ...int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldNotIn(FieldTrophyID, vs...))
}

// TrophyIDGT applies the GT predicate on the "trophy_id" field.
func TrophyIDGT(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldGT(FieldTrophyID, v))
}

// TrophyIDGTE applies the GTE predicate on the "trophy_id" field.
func TrophyIDGTE(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldGTE(FieldTrophyID, v))
}

// TrophyIDLT applies the LT predicate on the "trophy_id" field.
func TrophyIDLT(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldLT(FieldTrophyID, v))
}

// TrophyIDLTE applies the LTE predicate on the "trophy_id" field.
func TrophyIDLTE(v int) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldLTE(FieldTrophyID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.FieldLTE(FieldCreatedAt, v))
}

// HasGranted applies the HasEdge predicate on the "granted" edge.
func HasGranted() predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GrantedTable, GrantedColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGrantedWith applies the HasEdge predicate on the "granted" edge with a given conditions (other predicates).
func HasGrantedWith(preds ...predicate.USERS) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(func(s *sql.Selector) {
		step := newGrantedStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRefers applies the HasEdge predicate on the "refers" edge.
func HasRefers() predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RefersTable, RefersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRefersWith applies the HasEdge predicate on the "refers" edge with a given conditions (other predicates).
func HasRefersWith(preds ...predicate.TROPHIES) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(func(s *sql.Selector) {
		step := newRefersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ACHIEVEMENTS) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ACHIEVEMENTS) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ACHIEVEMENTS) predicate.ACHIEVEMENTS {
	return predicate.ACHIEVEMENTS(sql.NotPredicates(p))
}
