// Code generated by ent, DO NOT EDIT.

package users

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the users type in the database.
	Label = "users"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldIsDeleted holds the string denoting the is_deleted field in the database.
	FieldIsDeleted = "is_deleted"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeConnects holds the string denoting the connects edge name in mutations.
	EdgeConnects = "connects"
	// EdgeMakes holds the string denoting the makes edge name in mutations.
	EdgeMakes = "makes"
	// EdgePrepares holds the string denoting the prepares edge name in mutations.
	EdgePrepares = "prepares"
	// EdgeAcquires holds the string denoting the acquires edge name in mutations.
	EdgeAcquires = "acquires"
	// EdgeRecords holds the string denoting the records edge name in mutations.
	EdgeRecords = "records"
	// Table holds the table name of the users in the database.
	Table = "user_ss"
	// ConnectsTable is the table that holds the connects relation/edge. The primary key declared below.
	ConnectsTable = "users_connects"
	// ConnectsInverseTable is the table name for the FRIENDS entity.
	// It exists in this package in order to avoid circular dependency with the "friends" package.
	ConnectsInverseTable = "friend_ss"
	// MakesTable is the table that holds the makes relation/edge.
	MakesTable = "event_record_ss"
	// MakesInverseTable is the table name for the EVENT_RECORDS entity.
	// It exists in this package in order to avoid circular dependency with the "event_records" package.
	MakesInverseTable = "event_record_ss"
	// MakesColumn is the table column denoting the makes relation/edge.
	MakesColumn = "users_makes"
	// PreparesTable is the table that holds the prepares relation/edge.
	PreparesTable = "memo_ss"
	// PreparesInverseTable is the table name for the MEMOS entity.
	// It exists in this package in order to avoid circular dependency with the "memos" package.
	PreparesInverseTable = "memo_ss"
	// PreparesColumn is the table column denoting the prepares relation/edge.
	PreparesColumn = "users_prepares"
	// AcquiresTable is the table that holds the acquires relation/edge.
	AcquiresTable = "achievement_ss"
	// AcquiresInverseTable is the table name for the ACHIEVEMENTS entity.
	// It exists in this package in order to avoid circular dependency with the "achievements" package.
	AcquiresInverseTable = "achievement_ss"
	// AcquiresColumn is the table column denoting the acquires relation/edge.
	AcquiresColumn = "users_acquires"
	// RecordsTable is the table that holds the records relation/edge.
	RecordsTable = "progres_ss"
	// RecordsInverseTable is the table name for the PROGRESS entity.
	// It exists in this package in order to avoid circular dependency with the "progress" package.
	RecordsInverseTable = "progres_ss"
	// RecordsColumn is the table column denoting the records relation/edge.
	RecordsColumn = "users_records"
)

// Columns holds all SQL columns for users fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldAvatarURL,
	FieldRole,
	FieldCreatedAt,
	FieldIsDeleted,
	FieldUpdatedAt,
}

var (
	// ConnectsPrimaryKey and ConnectsColumn2 are the table columns denoting the
	// primary key for the connects relation (M2M).
	ConnectsPrimaryKey = []string{"users_id", "friends_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultIsDeleted holds the default value on creation for the "is_deleted" field.
	DefaultIsDeleted bool
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)

// Role defines the type for the "role" enum field.
type Role string

// Role values.
const (
	RoleSUPERUSER Role = "SUPERUSER"
	RoleADMIN     Role = "ADMIN"
	RoleUSER      Role = "USER"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleSUPERUSER, RoleADMIN, RoleUSER:
		return nil
	default:
		return fmt.Errorf("users: invalid enum value for role field: %q", r)
	}
}

// OrderOption defines the ordering options for the USERS queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByAvatarURL orders the results by the avatar_url field.
func ByAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarURL, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByIsDeleted orders the results by the is_deleted field.
func ByIsDeleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDeleted, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByConnectsCount orders the results by connects count.
func ByConnectsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newConnectsStep(), opts...)
	}
}

// ByConnects orders the results by connects terms.
func ByConnects(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConnectsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMakesCount orders the results by makes count.
func ByMakesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMakesStep(), opts...)
	}
}

// ByMakes orders the results by makes terms.
func ByMakes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMakesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPreparesField orders the results by prepares field.
func ByPreparesField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPreparesStep(), sql.OrderByField(field, opts...))
	}
}

// ByAcquiresCount orders the results by acquires count.
func ByAcquiresCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAcquiresStep(), opts...)
	}
}

// ByAcquires orders the results by acquires terms.
func ByAcquires(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAcquiresStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRecordsField orders the results by records field.
func ByRecordsField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecordsStep(), sql.OrderByField(field, opts...))
	}
}
func newConnectsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConnectsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ConnectsTable, ConnectsPrimaryKey...),
	)
}
func newMakesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MakesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MakesTable, MakesColumn),
	)
}
func newPreparesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PreparesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, PreparesTable, PreparesColumn),
	)
}
func newAcquiresStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AcquiresInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AcquiresTable, AcquiresColumn),
	)
}
func newRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, RecordsTable, RecordsColumn),
	)
}
